export const trendingMovies = [
  {
    id: 1,
    title: "Dune 2",
    imageUrl: require("./../assets/dune2.webp"),
    progress: 0.6,
    rating: 4.3,
    genres: ["Action"],
  },
  {
    id: 2,
    title: "Oppenheimer",
    imageUrl: require("./../assets/openhaimer.jpg"),
    rating: 3.8,
    genres: ["Thriller", "Drama"],
  },
  {
    id: 3,
    title: "Barbie",
    imageUrl: require("./../assets/barbie.jpg"),
    rating: 4.1,
    genres: ["Comedy", "Family"],
  },
  {
    id: 4,
    title: "Transformes",
    imageUrl: require("./../assets/transformers.jpg"),
    rating: 3.9,
    genres: ["Action"],
  },
  {
    id: 5,
    title: "Joker",
    imageUrl: require("./../assets/joker.jpg"),
    rating: 4.7,
    genres: ["Thriller"],
  },
  {
    id: 6,
    title: "Batman",
    imageUrl: require("./../assets/batman.jpg"),
    rating: 4.2,
    genres: ["Action"],
  },
  {
    id: 7,
    title: "BeeKeeper",
    imageUrl: require("./../assets/beekeeper.jpg"),
    rating: 3.5,
    genres: ["Horror"],
  },
  {
    id: 8,
    title: "Good Fellas",
    imageUrl: require("./../assets/goodfellas.jpg"),
    progress: 0.7,
    rating: 4.4,
    genres: ["Thriller"],
  },
  {
    id: 9,
    title: "Alien",
    imageUrl: require("./../assets/alien.jpg"),
    progress: 0.9,
    rating: 4.0,
    genres: ["Horror"],
  },
  {
    id: 10,
    title: "StarWars",
    imageUrl: require("./../assets/starwars.jpeg"),
    progress: 0.4,
    rating: 4.6,
    genres: ["Action"],
  },
  {
    id: 11,
    title: "Cars 1",
    imageUrl: require("./../assets/cars1.jpeg"),
    progress: 0.1,
    rating: 3.5,
    genres: ["Comedy", "Family", "Family"],
  },
  {
    id: 12,
    title: "Cars 2",
    imageUrl: require("./../assets/cars2.jpg"),
    progress: 0.9,
    rating: 4.0,
    genres: ["Comedy", "Family", "Family"],
  },
  {
    id: 13,
    title: "Cars 3",
    imageUrl: require("./../assets/cars3.jpeg"),
    rating: 3.8,
    genres: ["Comedy", "Family", "Family"],
  },
  {
    id: 14,
    title: "F&F 9",
    imageUrl: require("./../assets/f9.jpg"),
    rating: 4.2,
    genres: ["Action"],
  },
  {
    id: 15,
    title: "Avatar",
    imageUrl: require("./../assets/avatar.jpg"),
    rating: 4.8,
    genres: ["Family"],
  },
  {
    id: 16,
    title: "Ratatouille",
    imageUrl: require("./../assets/ratatui.jpeg"),
    rating: 4.5,
    genres: ["Comedy", "Family"],
  },
];
